### ISSUE TITLE
Game crashes when using the "taco bell"

### ISSUE THREAD

**Issue by flopingbird** [N1nn1/yippee#5]
Made a modpack with something around 80 mods and whenever we use the taco bell it crashes the server (server side only). Here is the crash report:
```
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 2022-08-09 16:47:29
Description: Exception in server tick loop

java.lang.ExceptionInInitializerError
	at com.ninni.yippee.block.entity.TacoBellBlockEntity.<init>(TacoBellBlockEntity.java:23)
	at com.ninni.yippee.block.TacoBellBlock.method_10123(TacoBellBlock.java:199)
	at net.minecraft.class_2818.method_12010(class_2818.java:268)
	at net.minecraft.class_1937.method_30092(class_1937.java:221)
	at net.minecraft.class_1937.method_8652(class_1937.java:206)
	at net.minecraft.class_1747.method_7708(class_1747.java:159)
	at net.minecraft.class_1747.method_7712(class_1747.java:76)
	at net.minecraft.class_1747.method_7884(class_1747.java:50)
	at net.minecraft.class_1799.method_7981(class_1799.java:264)
	at net.minecraft.class_3225.method_14262(class_3225.java:355)
	at net.minecraft.class_3244.method_12046(class_3244.java:1145)
	at net.minecraft.class_2885.method_12547(class_2885.java:34)
	at net.minecraft.class_2885.method_11054(class_2885.java:8)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:157)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159)
	at net.minecraft.class_1255.method_16075(class_1255.java:131)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752)
	at net.minecraft.class_1255.method_5383(class_1255.java:116)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:736)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:669)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalStateException: Registry is already frozen (trying to add key ResourceKey[minecraft:block_entity_type / yippee:taco_bell])
	at net.minecraft.class_2370.method_40274(class_2370.java:81)
	at net.minecraft.class_2370.method_31051(class_2370.java:91)
	at net.minecraft.class_2370.method_10273(class_2370.java:87)
	at net.minecraft.class_2370.method_10272(class_2370.java:135)
	at net.minecraft.class_2378.method_39197(class_2378.java:508)
	at net.minecraft.class_2378.method_10230(class_2378.java:504)
	at com.ninni.yippee.block.entity.YippeeBlockEntityType.<clinit>(YippeeBlockEntityType.java:12)
	... 27 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.19.1
	Minecraft Version ID: 1.19.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.2, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 2227747688 bytes (2124 MiB) / 3313500160 bytes (3160 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 32
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen Threadripper 2950X 16-Core Processor 
	Identifier: AuthenticAMD Family 23 Model 8 Stepping 2
	Microarchitecture: Zen+
	Frequency (GHz): 3.50
	Number of physical packages: 1
	Number of physical CPUs: 16
	Number of logical CPUs: 32
	Graphics card #0 name: Radeon RX 580 Series
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x67df
	Graphics card #0 versionInfo: DriverVersion=31.0.12015.1008
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 37525.14
	Virtual memory used (MB): 32855.93
	Swap memory total (MB): 4864.00
	Swap memory used (MB): 430.20
	JVM Flags: 1 total; -Xmx8G
	Fabric Mods: 
		ae2: Applied Energistics 2 12.1.0-alpha
			team_reborn_energy: Energy 2.0.0-beta1
		anthropophagy: Anthropophagy 1.19-2
			midnightlib: MidnightLib 0.5.2
			reach-entity-attributes: Reach Entity Attributes 2.3.0
		appleskin: AppleSkin 2.4.0+mc1.19
		architectury: Architectury 6.1.39
		bcc: BetterCompatibilityChecker 2.0.2-build.16+mc1.19.1
		bedspreads: Bedspreads 6.0.0+1.19.1
		betteranimalsplus: Better Animals Plus 1.19-11.0.7
		bookshelf: Bookshelf 15.0.1
		bottledair-fabric: Bottled Air (Fabric) 1.4
		camsbackpacks: Cammie's Wearable Backpacks 2.12
		cardinal-components: Cardinal Components API 5.0.1
			cardinal-components-base: Cardinal Components API (base) 5.0.1
			cardinal-components-block: Cardinal Components API (blocks) 5.0.1
			cardinal-components-chunk: Cardinal Components API (chunks) 5.0.1
			cardinal-components-entity: Cardinal Components API (entities) 5.0.1
			cardinal-components-item: Cardinal Components API (items) 5.0.1
			cardinal-components-level: Cardinal Components API (world saves) 5.0.1
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.0.1
			cardinal-components-world: Cardinal Components API (worlds) 5.0.1
		catsexpanded: Cats Expanded 1.2.2+1.19.0
		cloth-config: Cloth Config v8 8.0.75
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 9.0.0+10
		collective-fabric: Collective (Fabric) 4.36
			fiber: fiber 0.23.0-2
		compact_storage: Compact Storage 5.0.3-1.19.1
		corners: The Corners 1.2.3
			limlib: Liminal Library 6.3.1
		cosmetic-armor: Cosmetic Armor 1.4.0
		creativecore: CreativeCore (Fabric) 2.7.2
		darkutils: DarkUtilities 12.0.1
		dracomelette: Dracomelette 1.19-2
		easymagic: Easy Magic 4.1.0
		easyshulkerboxes: Easy Shulker Boxes 4.2.1
		elytraslot: Elytra Slot 6.0.0+1.19.1
		enchantinginfuser: Enchanting Infuser 4.1.1
		enderitemod: Enderite Mod 1.4.1
		enderitestorage: Enderite Reinforced Storage 1.0.3+1.19
		extraorigins: Extra Origins 1.19-2
		fabric: Fabric API 0.58.5+1.19.1
			fabric-api-base: Fabric API Base 0.4.9+e62f51a395
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.7+9ff28f4095
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.15+d5533c0195
			fabric-command-api-v1: Fabric Command API (v1) 1.2.9+f71b366f95
			fabric-command-api-v2: Fabric Command API (v2) 2.1.5+0c17ea9695
			fabric-commands-v0: Fabric Commands (v0) 0.2.26+df3654b395
			fabric-containers-v0: Fabric Containers (v0) 0.1.31+df3654b395
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.2.1+07df213e95
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.8+37622d2495
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.3+bd0a0d4a95
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.1.5+a680b9b495
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.28+a6d2f78595
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.16+9ff28f4095
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.26+9ff28f4095
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.26+df3654b395
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.19+1899036195
			fabric-item-api-v1: Fabric Item API (v1) 1.5.5+35a03c4395
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.26+9ff28f4095
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+33fbc73895
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.1+03a4e56895
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.4+9e7660c695
			fabric-message-api-v1: Fabric Message API (v1) 5.0.1+4e0178f495
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.11+33fbc73895
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.1+3082331495
			fabric-networking-v0: Fabric Networking (v0) 0.3.18+df3654b395
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.8+9ff28f4095
			fabric-particles-v1: Fabric Particles (v1) 1.0.8+dc39553a95
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.21+23c4cfef95
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.12+9ff28f4095
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.5+9ff28f4095
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.9+e62f51a395
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.6+5f1a85e095
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.10+9ff28f4095
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.0.9+e62f51a395
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.1+9e7660c695
		fabric-language-kotlin: Fabric Language Kotlin 1.8.2+kotlin.1.7.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.2
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.3
		fabricloader: Fabric Loader 0.14.9
		foodplusid: Food+ 1.4.1
		forgeconfigapiport: Forge Config API Port 4.1.4
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		geckolib3: Geckolib 3.1.13
			com_eliotlash_mclib_mclib: mclib 18
			com_eliotlash_molang_molang: molang 18
		hwg: Happiness is a Warm Gun 1.2.2
		immersive_portals: Immersive Portals 2.1.1
			imm_ptl_core: Immersive Portals Core 2.1.1
			q_misc_util: QMiscUtil 2.1.1
		incantationem: Incantationem 1.1.4+1.19
		ironchests: Iron Chests 1.7.6
			libgui: LibGui 6.0.0+1.19
				jankson: Jankson 4.1.1+j1.2.1
					blue_endless_jankson: jankson 1.2.1
				libninepatch: LibNinePatch 1.1.0
		java: Java HotSpot(TM) 64-Bit Server VM 17
		jei: Just Enough Items 11.2.0.244
		linearxp: Linear XP 1.0.1
		lithium: Lithium 0.8.3
		mcda: MC Dungeons Armors 2.1.1
		mcdw: MC Dungeons Weapons 4.4.1-1.19
			enchant_giver: Enchant Giver 1.3.0
		memoryleakfix: memory Leak Fix 1.19.1-0.7.0
		mendable_anvils: Mendable Anvils 1.0.0
		minecraft: Minecraft 1.19.1
		moborigins: Mob Origins 1.9.0
		netheritebeacons: Netherite Beacons 1.2.0
		no-autojump: No Autojump 1.0
		nochatreports: No Chat Reports 1.19.1-v1.8.4
		noenchantcap: No Enchant Cap 2.1.2+1.19
		origins: Origins 1.6.2
			apoli: Apoli 2.5.1
				additionalentityattributes: Additionalentityattributes 1.0.0+1.19
				calio: Calio 1.7.0
				playerabilitylib: Pal 1.6.0
		origins-classes: Origins: Classes 1.4.0
		parkbuilder: Parkbuilder: Hammond's Dream fabric-0.1.2
		pehkui: Pehkui 3.3.3+1.14.4-1.19.1
			kanos_config: Kanos Config 0.3.1+1.14.4-1.19
		pigpen: PigPen 10.0.1
		plushables: Plushables 0.1.1
		probablychests: Probably Chests 0.5.3-1.19.1
		puzzleslib: Puzzles Lib 4.1.6
		reinfbarrel: Reinforced Barrels 2.1.0+1.19
			reinfcore: Reinforced Core 2.1.1+1.19
		reinfchest: Reinforced Chests 2.0.4+1.19
		reinfshulker: Reinforced Shulker Boxes 2.0.4+1.19
		ring_of_enderchest: Ring of Enderchest 1.3.10
		runelic: Runelic 13.0.1
		sandwichable: Sandwichable 1.3.a+1.19
		splatus_spellbound_weapons: Spellbound Weapons 3.3.4
		toms_storage: Tom's Simple Storage Mod 1.3.5
		toolstats: ToolStats 11.0.2
		trinkets: Trinkets 3.4.0
		universal-graves: Universal Graves 2.1.1+1.19.1
			common-protection-api: Common Protection API 1.0.0
			fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
			hologram-api: Hologram API 0.2.2+1.19
			placeholder-api: Placeholder API 2.0.0-beta.7+1.19
			polymer: Polymer (Core) 0.2.10+1.19.1
				packet_tweaker: Packet Tweaker 0.3.0+1.18.2
				polymer-registry-sync-manipulator: Polymer Registry Sync Manipulator 0.0.1+1.19.1
			server_translations_api: Server Translations API 1.4.16+1.19
			sgui: sgui 1.1.3+1.19.1
		universalbonemeal: Universal Bone Meal 4.1.0
		visualworkbench: Visual Workbench 4.1.0
		voicechat: Simple Voice Chat 1.19.1-2.3.2
		wardenloot: Warden Loot 1.1.2-1.19.x
		wolveswitharmor: Wolves With Armor 1.8.0-1.19
			maybe-data: Maybe data 1.3.2-1.19-rc2
			static-content: Static Content 1.0.1-1.16.2
				staticdata: Static Data 1.1.2
		yippee: Yippee 1.2.0-fabric
	Server Running: true
	Player Count: 2 / 15; [class_3222['dribgnipolf'/242, l='ServerWorld minecraft:overworld world', x=-61.57, y=77.00, z=-3.43], class_3222['notxaJ'/92, l='ServerWorld minecraft:overworld world', x=-48.48, y=78.50, z=-7.53]]
	Data Packs: vanilla, Fabric Mods
	World Generation: Experimental
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)
```

honestly if this is intentional its pretty funny and if its not you should keep this
thanks in advance
fgooodbye
hello
w

j

**Comment by Lhruggles** [comment]
I am having the same issue. Hope it gets fixed, as I love this mod!

**Comment by Pandacatgamer** [comment]
Im also having this issue- it sucks because taco bell was the best item :(
